### ISSUE TITLE
How to run app locally with HANA Cloud?

### ISSUE THREAD

**Issue by js1972** [saphanaacademy/generator-saphanaacademy-cap#1]
Hi. Firstly thanks for this wonderful generator - excellent!

I'm wondering how to run the app locally. Obviously I can just do `cds watch` and I can run the app on localhost using an SQLite in-memory db. 

But CAP has the ability to do this with the real HANA DB, yet still run the service locally. According to the CAP docs here: https://cap.cloud.sap/docs/guides/databases. you can execute:
```
cds deploy --to hana
cds watch --production
```

But then I hit errors as it cannot find the xsuaa service. This is where I am stuck. I've tried using the CF DefaultEnv plugin and it does get around the authentication issue however I can no longer run the embedded html applications as they just give error like this:

```
Cannot GET /resources/html5/catalog/userInfo()
```

For some reason `/resources` gets added to the paths and that seems to be stuffing it up.

So I'm wondering if you know the "best" way to continue to develop an app from this generator - locally?

**Comment by saphanaacademy** [comment]
G'day Jason,

Thanks for using the generator and asking the question.

Have you seen this tutorial which covers [local development](https://www.youtube.com/watch?v=4G48r2_K_RU&list=PLkzo92owKnVxiagp35AcwoxOlX0J4hLyY&index=10)?

The recommended approach is to build and deploy the project to Cloud Foundry, then use DefaultEnv to create a local default-env.json file, set CAP to use the "production" profile with cmd `export CDS_ENV=production` then use `cds watch` or `cds run`. 

Best way to access the UI is to use the auto-generated links in the "Web Applications" section of `http://localhost:4004` and authenticate using one of the local test users eg: joe defined in package.json.

In most cases this should suffice.

Thanks.

**Comment by js1972** [comment]
Hi, I have watched those local development videos you linked but the app is structured differently. Apps generated by this yeoman generator have this XS-app.json:
```
{
    "welcomeFile": "index.html",
    "authenticationMethod": "route",
    "routes": [
        {
            "source": "^/catalog/(.*)$",
            "csrfProtection": false,
            "authenticationType": "xsuaa",
            "destination": "jasonhanaapp-srv"
        },
        {
            "source": "^/(.*)$",
            "authenticationType": "xsuaa",
            "service": "html5-apps-repo-rt"
        }
    ]
}
```

So in may app/default-env.json I add this to match:
```
"destinations": "[ {\n  \"forwardAuthToken\" : true,\n  \"name\" : \"jasonhanaapp-srv\",\n  \"url\" : \"http://localhost:5001\"\n} ]",
```

Now I start the local service with `cds watch --production` and this connects to the real hana db.
Then I start the approuter in /app with `npm start`.
When I goto the approuter I get the proper xsuaa redirect which is all good. Note that I need to adjust the path slightly and remove the "resources" part like so: `http://localhost:5000/html5/index.html`.

This shows the index page well. But when I click any links that call into the CAP SRV it fails with "not found" error.

So the difference in architecture here is that in the local development YouTube videos from Philip there is no destinations created and the MTA just refers to srv-api. Whereas with this generator there seems to be a bunch of destinations created and one of them: `jasonhanaapp-srv` is referenced in the XS-app.json as copied above.

**Comment by saphanaacademy** [comment]
Hi,
Are you using SAP Business Application Studio or pure local development such as with Visual Studio Code?
It looks like the project is using the HTML5 repository and it's own project app router rather than the managed app router. Is that correct?
Would you be able to share the entire project or the answers to the prompts when using the generator - so we can try to reproduce the issue?
Thanks.

**Comment by js1972** [comment]
I have solved the issue and it was mainly just my lack of understanding. I was trying to run approuter locally which was causing the above issue.

By simply running `cf de jasonhanaapp-srv` to download the HANA Cloud credentials from cloud foundry into a default-env.json file it all worked using HANA Cloud as the DB instead of SQLite. I could run the app with `CDS_ENV=production cds watch`.

Thanks for your help.
