### ISSUE TITLE
OData v2 support not working. "kind" is set to "odata" instead of "odata-v2"

### ISSUE THREAD

**Issue by kepair** [saphanaacademy/generator-saphanaacademy-cap#2]
Hi team,

When using SFSF as external source and setting _OData v2 support_ to true in the wizard, the `kind` attribute is set to `odata`:
```json
"RCMCandidate": {
        "kind": "odata",
        "model": "srv/external/RCMCandidate",
        "credentials": {
          "[production]": {
            "destination": "sfsfcapapp-sf-api",
            "path": "odata/v2"
          },
          "[development]": {
            "url": "https://sandbox.api.sap.com/successfactors/odata/v2"
          }
        }
      }
```
This will break a Fiori Elements app, see:
https://answers.sap.com/questions/13530425/fiori-elements-list-not-showing-data-batch-request.html

When I set _OData v2 support_ to true, I'm expecting the `kind` to be set to `odata-v2`, as stated in CAP docs:

>You can consume OData V2 services with Node.js, by setting kind to odata-v2.

https://cap.cloud.sap/docs/releases/oct21#consuming-odata-v2-services-in-nodejs

Thanks,
Pedro

**Comment by saphanaacademy** [comment]
​Hi Pedro,

Thanks for raising this, watching the HANA Academy tutorials and using the CAP generator. The option _"kind": "odata-v2"_ is quite recent and was only added to CAP in the October release.

However we have now incorporated it into the CAP generator (0.0.54) for the S/4HANA Cloud & SuccessFactors API examples as they are indeed accessing OData v2 services.

To be clear, the option _"Would you like to enable OData v2 support?"_ asks whether you would like **all** the OData services you are **providing** as part of your CAP application to be served as OData v2 in addition to OData v4 by configuring the CAP OData v2 Proxy. 

This is different to the _"kind": "odata-v2/odata/rest"_ option in CAP which is explicitly configured for each external service you are **accessing**.

Thanks

**Comment by kepair** [comment]
Thanks for the update and clarification.

Oh ok, the _OData v2 support_ is referring to CAP serving OData v2 (as documented [here](https://cap.cloud.sap/docs/advanced/odata#odata-v2-proxy-node))
>To be clear, the option "Would you like to enable OData v2 support?" asks whether you would like all the OData services you are providing as part of your CAP application to be served as OData v2 in addition to OData v4 by configuring the CAP OData v2 Proxy.

I must say, this generator does a lot of heavy lifting work, is really nice.

Thanks,
Pedro
