### ISSUE TITLE
Can't use the Show Page Map from BAS.

### ISSUE THREAD

**Issue by eddiedu** [saphanaacademy/generator-saphanaacademy-cap#3]
HI experts.

Do you think it is possible to add to the generator the parameters so the Fiori Elements plugins recognize the Fiori app as a Fiori application?

Doing some research I found the missing configuration is to add at the bottom of the package JSON:
"sapux" : [
  "app/fiori",
]

But this doesn't seem to be not enough, because now it knows that there is a Fiori app but it opens a blank page:
![image](https://user-images.githubusercontent.com/2708209/152209225-19c04477-52d5-4da8-8a8a-faa20d83cfdc.png)

One thing that I found is if you add another Fiori project in the MTA and add again the Fiori app at the bottom of the package.json it will start to work.

Thanks and best regards,
Edu

**Comment by saphanaacademy** [comment]
Hi Edu,
Thanks for your request and using the SAP HANA Academy content. We're looking into it and hope to cover this topic in the near future.
Regards,
Philip

**Comment by saphanaacademy** [comment]
Hi @eddiedu,
This should be working now (v0.0.66).
You can install via `npm install -g generator-saphanaacademy-cap`
Thanks & best regards,
Philip
