### ISSUE TITLE
Unable to use with existing HDI Containers

### ISSUE THREAD

**Issue by brianles113** [saphanaacademy/generator-saphanaacademy-cap#6]
While attempting to use this generator for an existing HDI Container, once I enter a hdi service name, I'm no longer presented with options to add the schema, url etc..

I've tried this via command line and with UI in SAP Business Application Studio.

**Comment by saphanaacademy** [comment]
Hello,

Thanks for trying the generator and reaching out.

When you enter a value for "Will you be using an existing SAP HANA Cloud HDI Container?" it's completely normal not to be prompted for schema name or endpoint URL as that's for accessing an existing SAP HANA Cloud "classical" schema.

See the video tutorial [here](https://www.youtube.com/watch?v=l9pwWeElmeY&list=PLkzo92owKnVwQ-0oT78691fqvHrYXd5oN&t=446).

For everything to work properly it's essential that you're already logged into Cloud Foundry and targeting the org & space where the existing HDI container service instance has been deployed to _before_ starting the generator. This is also covered earlier in the same video tutorial [here](https://www.youtube.com/watch?v=l9pwWeElmeY&list=PLkzo92owKnVwQ-0oT78691fqvHrYXd5oN&t=325).

Does that help?

Thanks.
